import '@/styles/legal.css';
import '@/styles/blog.css'; // Reusing blog layout styles for TOC and grid

export const metadata = {
  title: 'Disclaimer',
  description: 'ToolTive Disclaimer.',
  alternates: { canonical: '/disclaimer' },
};

export default function Disclaimer() {
  return (
    <div className="container blog-page-container">
      <div className="blog-layout">
        
        {/* Main Content (65%) */}
        <article className="blog-article legal-page" style={{ padding: '0', maxWidth: '100%', margin: '0' }}>
          <h1>Disclaimer</h1>
          <p className="legal-date"><strong>Last Updated: August 9, 2026</strong></p>

          <p>ToolTive (“ToolTive,” “we,” “us,” or “our”) operates <strong><a href="https://tooltive.com">https://tooltive.com</a></strong> and provides free online tools and utilities for general informational and practical purposes.</p>
          <p>This Disclaimer explains important limitations regarding the information, tools, processing, and outputs provided through ToolTive.</p>

          <h2 id="general">1. General Information</h2>
          <p>The information and tools available on ToolTive are provided for general informational and practical purposes.</p>
          <p>While we aim to maintain useful, functional, and accurate tools and information, ToolTive does not guarantee that every tool, result, description, calculation, conversion, or piece of information will always be complete, accurate, current, or suitable for a particular purpose.</p>
          <p>Users should review important results before relying on them.</p>

          <h2 id="tool-results">2. Tool Results and Accuracy</h2>
          <p>ToolTive provides utilities for tasks such as image compression, PDF conversion, invoice generation, and other online functions.</p>
          <p>Results may vary depending on the input, browser, device, tool configuration, file characteristics, or other technical factors.</p>
          <p>ToolTive does not guarantee that generated or processed results will be free from errors or suitable for every particular use.</p>
          <p>Users are responsible for reviewing and verifying any output generated by ToolTive before relying on it, publishing it, submitting it, distributing it, or using it for business, financial, legal, or other important purposes.</p>

          <h2 id="user-responsibility">3. User Responsibility</h2>
          <p>Users are responsible for how they use ToolTive and for the content they process through the website.</p>
          <p>Before processing or using any content, users are responsible for ensuring that they have the necessary rights, permissions, licenses, or authority to use that content.</p>
          <p>Users are also responsible for complying with applicable laws, regulations, contractual obligations, intellectual-property rights, privacy rights, and other applicable requirements.</p>
          <p>ToolTive does not determine whether a user's particular use of content is legally permitted.</p>

          <h2 id="generated-documents">4. Generated Documents and Business Tools</h2>
          <p>ToolTive may provide tools that generate invoices, quotes, credit notes, PDFs, images, or other documents.</p>
          <p>These tools are provided for convenience and document-generation purposes.</p>
          <p>Generated documents should be reviewed and customized by the user before they are used for business, accounting, tax, financial, legal, or other official purposes.</p>
          <p>ToolTive's invoice and business-document tools do not constitute accounting, tax, financial, legal, or professional advice.</p>
          <p>Users are responsible for ensuring that documents they create or use comply with the requirements applicable to their particular business, transaction, location, or situation.</p>

          <h2 id="no-professional-advice">5. No Professional Advice</h2>
          <p>Nothing provided through ToolTive should be considered legal, tax, accounting, financial, medical, or other professional advice.</p>
          <p>If you require professional advice or need to determine whether a particular action, document, calculation, or use of content complies with applicable requirements, you should consult an appropriately qualified professional.</p>

          <h2 id="browser-processing">6. Browser-Based Processing</h2>
          <p>Many ToolTive tools are designed to process files directly within the user's web browser.</p>
          <p>Where a tool operates entirely on the client side, the selected files remain within the browser during processing and are not uploaded to ToolTive's servers for processing.</p>
          <p>ToolTive does not currently operate a custom backend file-processing API through which user files are routinely transmitted.</p>
          <p>Users should nevertheless review the functionality of the particular tool they are using and should maintain their own backups of important files.</p>

          <h2 id="user-files">7. User Files and Content</h2>
          <p>ToolTive does not claim ownership of files, documents, images, text, or other content that users process through its tools.</p>
          <p>Users retain responsibility for the content they provide and the rights associated with that content.</p>
          <p>Users should not process content through ToolTive unless they have the necessary rights or permissions to do so.</p>
          <p>Users are also responsible for maintaining independent copies or backups of important files. ToolTive should not be treated as a permanent file-storage or backup service.</p>

          <h2 id="third-party">8. Third-Party Websites and Services</h2>
          <p>ToolTive may link to or reference third-party websites, services, resources, or technologies.</p>
          <p>ToolTive does not control third-party websites or services and is not responsible for their content, availability, accuracy, security, privacy practices, terms, or policies.</p>
          <p>A link or reference to a third-party service does not necessarily mean that ToolTive endorses or guarantees that service.</p>
          <p>Users should review the applicable terms and privacy policies of third-party services before using them.</p>

          <h2 id="availability">9. Website Availability and Technical Limitations</h2>
          <p>ToolTive may occasionally experience interruptions, maintenance, technical issues, browser compatibility problems, network failures, or other circumstances that affect the availability or functionality of the website or individual tools.</p>
          <p>ToolTive does not guarantee uninterrupted or permanent availability of the website or any particular tool.</p>
          <p>Features, tools, technologies, and functionality may be changed, updated, suspended, or discontinued as the website develops.</p>

          <h2 id="security">10. Security and Data Processing</h2>
          <p>ToolTive uses HTTPS and infrastructure and security technologies intended to help protect the website and its users.</p>
          <p>However, no website, network, browser, or electronic transmission can be guaranteed to be completely secure.</p>
          <p>Where ToolTive tools process files locally in the browser, those files are not transmitted to ToolTive servers for processing by the audited client-side tools.</p>
          <p>Users remain responsible for using appropriate care when selecting files, devices, browsers, and networks for their particular circumstances.</p>

          <h2 id="ip">11. Intellectual Property and Third-Party Rights</h2>
          <p>Users are responsible for ensuring that the content they process, modify, convert, compress, reproduce, or otherwise use through ToolTive does not infringe the intellectual-property or other rights of another person or organization.</p>
          <p>ToolTive does not assume responsibility for determining whether user-provided content is protected by copyright, trademark, privacy rights, publicity rights, or other legal protections.</p>
          <p>Users should obtain appropriate permission before processing or using content when permission is required.</p>

          <h2 id="commercial">12. Commercial Use</h2>
          <p>ToolTive's tools are currently provided free of charge, and users may generally use generated outputs for legitimate personal or commercial purposes.</p>
          <p>Commercial use remains subject to applicable laws, third-party rights, and the user's responsibility to review and verify generated outputs.</p>
          <p>ToolTive does not guarantee that a generated document or output will satisfy the specific legal, accounting, tax, commercial, or regulatory requirements of a particular business or jurisdiction.</p>

          <h2 id="changes-tooltive">13. Changes to ToolTive</h2>
          <p>ToolTive may add, remove, modify, replace, or update tools, features, information, processing methods, and other website functionality.</p>
          <p>The behavior or capabilities of an individual tool may therefore change over time.</p>
          <p>This Disclaimer applies to the ToolTive services and functionality available at the time of use.</p>

          <h2 id="changes-disclaimer">14. Changes to This Disclaimer</h2>
          <p>We may update this Disclaimer from time to time to reflect changes to ToolTive, its tools, features, services, or applicable requirements.</p>
          <p>When material changes are made, the Last Updated date at the top of this page will be updated.</p>
          <p>Users are encouraged to review this page periodically for the latest information.</p>

          <h2 id="limitation">15. Limitation of Responsibility</h2>
          <p>To the extent permitted by applicable law, ToolTive is not responsible for losses, damages, or consequences arising from reliance on information, tools, calculations, conversions, generated documents, processed files, or other results provided through the website.</p>
          <p>Users are responsible for independently reviewing important outputs and determining whether they are appropriate for their intended use.</p>
          <p>Nothing in this Disclaimer is intended to exclude or limit liability where such exclusion or limitation is not permitted by applicable law.</p>

          <h2 id="contact">16. Contact Us</h2>
          <p>If you have questions regarding this Disclaimer or the use of ToolTive, you may contact us:</p>
          <p>
            <strong>ToolTive</strong><br />
            <strong>Email:</strong> <a href="mailto:support@tooltive.com">support@tooltive.com</a><br />
            <strong>Website:</strong> <a href="https://tooltive.com">https://tooltive.com</a>
          </p>
          <p>We will make reasonable efforts to review and respond to relevant inquiries.</p>
        </article>

        {/* Sidebar / Table of Contents (30%) */}
        <aside className="blog-sidebar">
          <div className="toc-box">
            <h3 className="toc-title">Table of Contents</h3>
            <ul className="toc-list">
              <li><a href="#general">1. General Information</a></li>
              <li><a href="#tool-results">2. Tool Results and Accuracy</a></li>
              <li><a href="#user-responsibility">3. User Responsibility</a></li>
              <li><a href="#generated-documents">4. Generated Documents</a></li>
              <li><a href="#no-professional-advice">5. No Professional Advice</a></li>
              <li><a href="#browser-processing">6. Browser-Based Processing</a></li>
              <li><a href="#user-files">7. User Files and Content</a></li>
              <li><a href="#third-party">8. Third-Party Services</a></li>
              <li><a href="#availability">9. Website Availability</a></li>
              <li><a href="#security">10. Security and Data</a></li>
              <li><a href="#ip">11. Intellectual Property</a></li>
              <li><a href="#commercial">12. Commercial Use</a></li>
              <li><a href="#changes-tooltive">13. Changes to ToolTive</a></li>
              <li><a href="#changes-disclaimer">14. Changes to Disclaimer</a></li>
              <li><a href="#limitation">15. Limitation of Responsibility</a></li>
              <li><a href="#contact">16. Contact Us</a></li>
            </ul>
          </div>
        </aside>

      </div>
    </div>
  );
}
